controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  type: diff_drive_controller/DiffDriveController
  ros__parameters:
    left_wheel_names: ["body_to_lf_wheel", "body_to_lb_wheel"]
    right_wheel_names: ["body_to_rf_wheel", "body_to_rb_wheel"]
    wheel_separation: 0.54  # ${body_y - 2*wheel_len}
    wheels_radius: 0.125   # ${wheel_radius}
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 50.0