<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="simple_box_bot">

  <!-- All include file used -->

  <xacro:include filename="lidar.xacro" />
  
  <!-- Structure of the Main body -->

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}" />
      </geometry>
      <material name="almost_green" />
      <origin xyz="0 0 ${body_z / 2 + wheel_radius }" rpy="0 0 0" />
    </visual>
    
    <collision>
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}" />
      </geometry>
      <origin xyz="0 0 ${body_z / 2 + wheel_radius }" rpy="0 0 0" />
    </collision>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="${body_mass}"/>
      <inertia
        ixx="${(1/12)*body_mass*(body_y*body_y + body_z*body_z)}"
        ixy="0"
        ixz="0"
        iyy="${(1/12)*body_mass*(body_x*body_x+body_z*body_z)}"
        iyz="0"
        izz="${(1/12)*body_mass*(body_y*body_y+body_x*body_x)}"
      />
    </inertial>

  </link>

  <!-- Right Front wheel Structure and joint -->

  <link name="rf_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <material name="almost_blue" />
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>

    <xacro:inertia_wheel />

  </link>

  <joint name="body_to_rf_wheel" type="continuous">
    <parent link="base_link" />
    <child link="rf_wheel" />
    <origin xyz="${body_x/2 - 1.2*wheel_radius} ${-body_y/2 + wheel_len} ${wheel_z}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Right Back Wheel Structure and Joint -->
  
  <link name="rb_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <material name="almost_blue" />
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>

    <xacro:inertia_wheel />

  </link>

  <joint name="body_to_rb_wheel" type="continuous">
    <parent link="base_link" />
    <child link="rb_wheel" />
    <origin xyz="${-body_x/2 + 1.2*wheel_radius} ${-body_y/2 + wheel_len} ${wheel_z}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Left Front Wheel Structure and Joint -->
  
  <link name="lf_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <material name="almost_blue" />
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>

    <xacro:inertia_wheel />

  </link>

  <joint name="body_to_lf_wheel" type="continuous">
    <parent link="base_link" />
    <child link="lf_wheel" />
    <origin xyz="${body_x/2 - 1.2*wheel_radius} ${body_y/2 - wheel_len} ${wheel_z}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Left Back Structure and Joint -->

  <link name="lb_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <material name="almost_blue" />
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>

    <xacro:inertia_wheel />

  </link>

  <joint name="body_to_lb_wheel" type="continuous">
    <parent link="base_link" />
    <child link="lb_wheel" />
    <origin xyz="${-body_x/2 + 1.2*wheel_radius} ${body_y/2 - wheel_len} ${wheel_z}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

</robot>
