<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="simple_box_bot_gazebo">

  <!-- ROS 2 Control -->
  <ros2_control name="diff_drive_controller" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="body_to_lf_wheel">
      <command_interface name="velocity"/>
    </joint>
    <joint name="body_to_lb_wheel">
      <command_interface name="velocity"/>
    </joint>
    <joint name="body_to_rf_wheel">
      <command_interface name="velocity"/>
    </joint>
    <joint name="body_to_rb_wheel">
      <command_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
  </gazebo>

  <!-- Differential Drive Plugin (FIXED CONFIG) -->
  <gazebo>
    <plugin filename="libignition-gazebo-diff-drive-system.so" name="ignition::gazebo::systems::DiffDrive">
      <left_joint>body_to_lf_wheel</left_joint>
      <left_joint>body_to_lb_wheel</left_joint>
      <right_joint>body_to_rf_wheel</right_joint>
      <right_joint>body_to_rb_wheel</right_joint>
      <wheel_separation>${body_y - 2*wheel_len}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <topic>/model/simple_box_robo/cmd_vel</topic>  <!-- ABSOLUTE TOPIC -->
      <odom_topic>odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <!-- GPU LIDAR -->
  <gazebo reference="lidar_body">
    <sensor name="gpu_lidar" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <topic>scan</topic>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>6.28319</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin filename="libignition-gazebo-gpu-lidar-system.so" 
              name="ignition::gazebo::systems::GpuLidar">
        <topic>scan</topic>
        <frame_name>lidar_body</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Camera -->
  <gazebo reference="camera_link">
    <sensor name="camera_sensor" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <camera name="camera">
        <horizontal_fov>1.0472</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <plugin filename="libignition-gazebo-camera-system.so" 
              name="ignition::gazebo::systems::Camera">
        <topic>camera/image</topic>
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Wheel Physics (CRITICAL ADDITION) -->
  <gazebo reference="rf_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lf_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rb_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lb_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>