<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="simple_box_bot_gazebo">

  <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin filename="libignition-gazebo-diff-drive-system.so" name="ignition::gazebo::systems::DiffDrive">
      <left_joint>body_to_lf_wheel</left_joint>
      <left_joint>body_to_lb_wheel</left_joint>
      <right_joint>body_to_rf_wheel</right_joint>
      <right_joint>body_to_rb_wheel</right_joint>
      <wheel_separation>${body_y - 2*wheel_len}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <!-- Keyboard Control Plugins -->
  <gazebo>
    <!-- Forward (Up Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777235</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/cmd_vel">
        linear: {x: 0.5}, angular: {z: 0.0}
      </output>
    </plugin>

    <!-- Backward (Down Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777237</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/cmd_vel">
        linear: {x: -0.5}, angular: {z: 0.0}
      </output>
    </plugin>

    <!-- Left (Left Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777234</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/cmd_vel">
        linear: {x: 0.0}, angular: {z: 1.0}
      </output>
    </plugin>

    <!-- Right (Right Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777236</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/cmd_vel">
        linear: {x: 0.0}, angular: {z: -1.0}
      </output>
    </plugin>

    <!-- Stop Signal (S)-->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">83</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/cmd_vel">
        linear: {x: 0.0}, angular: {z: 0.0}
      </output>
    </plugin>

  </gazebo>

  <!-- Wheel Physics -->
  <gazebo reference="rf_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lf_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rb_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lb_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>