<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="simple_box_bot_gazebo">

  <!-- Sensors System Plugin (MUST be top-level) -->

  <!-- Joint State Publisher -->
  <plugin filename="libignition-gazebo-joint-state-publisher-system.so"
          name="ignition::gazebo::systems::JointStatePublisher">
  </plugin>

  <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin filename="libignition-gazebo-diff-drive-system.so" name="ignition::gazebo::systems::DiffDrive">
      <left_joint>body_to_lf_wheel</left_joint>
      <left_joint>body_to_lb_wheel</left_joint>
      <right_joint>body_to_rf_wheel</right_joint>
      <right_joint>body_to_rb_wheel</right_joint>
      <wheel_separation>${body_y - 2*wheel_len}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <!-- Keyboard Control Plugins -->
  <gazebo>
    <!-- Forward (Up Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777235</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/keyboard_cmd">
        linear: {x: 0.5}, angular: {z: 0.0}
      </output>
    </plugin>

    <!-- Backward (Down Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777237</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/keyboard_cmd">
        linear: {x: -0.5}, angular: {z: 0.0}
      </output>
    </plugin>

    <!-- Left (Left Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777234</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/keyboard_cmd">
        linear: {x: 0.0}, angular: {z: 2.5}
      </output>
    </plugin>

    <!-- Right (Right Arrow) -->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777236</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/keyboard_cmd">
        linear: {x: 0.0}, angular: {z: -2.5}
      </output>
    </plugin>

    <!-- Stop Signal (S)-->
    <plugin filename="libignition-gazebo-triggered-publisher-system.so"
            name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">83</match>
      </input>
      <output type="ignition.msgs.Twist" topic="/keyboard_cmd">
        linear: {x: 0.0}, angular: {z: 0.0}
      </output>
    </plugin>

  </gazebo>

  <!-- ROS-Ignition Bridge for LiDAR -->
  

  <!-- LiDAR Sensor -->
  <gazebo reference="lidar_body">
    <sensor name="lidar_sensor" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <topic>lidar</topic>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>640</samples>
            <resolution>1</resolution>
            <min_angle>${-PI}</min_angle>  
            <max_angle>${PI}</max_angle>    
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>0.01</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.08</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <plugin filename="libignition-gazebo-sensors-system.so"
          name="ignition::gazebo::systems::Sensors">
        <render_engine>ogre2</render_engine>
      </plugin>
      <plugin filename="libignition-gazebo-joint-controller-system.so"
          name="ignition::gazebo::systems::JointController">
        <joint_name>rod_to_lidar</joint_name>
        <use_velocity_control>false</use_velocity_control>
        <use_position_control>true</use_position_control>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Camera Plugins -->
  <gazebo reference="camera_link">
    <sensor name="camera_sensor" type="camera">
      <pose>0 0 0 0 0 0</pose>  <!-- Adjust if camera is offset -->
      <camera>
        <horizontal_fov>1.047</horizontal_fov>  <!-- 60Â° FOV -->
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <topic>camera/image_raw</topic>  <!-- ROS 2 topic -->
      <plugin filename="libignition-gazebo-camera-system.so"
              name="ignition::gazebo::systems::Camera">
        <ros>
          <namespace>/</namespace>
          <remapping>~/image_raw:=camera/image_raw</remapping>
        </ros>
      </plugin>
    </sensor>
  </gazebo>



  <!-- Wheel Physics -->
  <gazebo reference="rf_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lf_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rb_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lb_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>