<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="simple_box_bot_gazebo">

  <!-- ========== GAZEBO EXTENSIONS ========== -->
  <!-- Required sensors system plugin -->
  <gazebo>
    <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
  </gazebo>

  <!-- Differential Drive Plugin (unchanged, already correct) -->
  <gazebo>
    <plugin filename="libignition-gazebo-diff-drive-system.so" name="ignition::gazebo::systems::DiffDrive">
      <left_joint>body_to_lf_wheel</left_joint>
      <left_joint>body_to_lb_wheel</left_joint>
      <right_joint>body_to_rf_wheel</right_joint>
      <right_joint>body_to_rb_wheel</right_joint>
      <wheel_separation>${body_y - 2*wheel_len}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <!-- GPU LIDAR (updated for Ignition Gazebo) -->
  <gazebo reference="lidar_body">
    <sensor name="gpu_lidar" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <topic>scan</topic>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>6.28319</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin 
        filename="libignition-gazebo-gpu-lidar-system.so" 
        name="ignition::gazebo::systems::GpuLidar">
        <topic>scan</topic>
        <frame_name>lidar_body</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Camera (updated plugin syntax) -->
  <gazebo reference="camera_link">
    <sensor name="camera_sensor" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <camera name="camera">
        <horizontal_fov>1.0472</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin 
        filename="libignition-gazebo-camera-system.so" 
        name="ignition::gazebo::systems::Camera">
        <topic>camera/image</topic>
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Gazebo materials (unchanged) -->
  <gazebo reference="base_link">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="rod">
    <material>Gazebo/White</material>
  </gazebo>
  <gazebo reference="lidar_body">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="rf_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rb_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lf_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="lb_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>